app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = "HiPy Administration"
admin.site.site_title = "HiPy Administration"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('front.urls')),
    path('foundation/', include('foundation.urls')),
    path('foundation2/', include('foundation2.urls')),
    #path('lifesci/', include('lifesci.urls')),
    path('accounts/', include('allauth.urls')),
    path('jurassichack/', include('jurassichack.urls'))
    
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/jurassichack/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'jurassichack'

urlpatterns = [
    path('', views.index, name='index'),
    path('reset/', views.reset, name='reset'),
    path('console/', views.console, name='console'),
    path('<str:character_name>/', views.character, name='character'),
    path('input/<int:answer_id>/', views.input, name='input')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/jurassichack/models.py
from django.db import models
from django.core.exceptions import ValidationError

class Hack(models.Model):
    name = models.CharField(max_length=128, unique=True)
    start = models.DateTimeField()
    finish = models.DateTimeField()

    def __str__(self):
        return self.name
    
    def clean(self):
        # Check for overlapping records
        overlapping_hacks = Hack.objects.filter(
            finish__gt=self.start, # Existing finish is after new start
            start__lt=self.finish # Existing start is before new finish
        )

        if self.pk: # Exclude the current instance from the query if updating
            overlapping_hacks = overlapping_hacks.exclude(pk=self.pk)

        if overlapping_hacks.exists():
            raise ValidationError("Another hack overlaps with the specified time range.")
        
    def save(self, *args, **kwargs):
        # Call clean to validate before saving
        self.clean()
        super().save(*args, **kwargs)
    
class Character(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name
    
class Question(models.Model):
    name = models.CharField(max_length=128, unique=True)
    title = models.CharField(max_length=128, blank=True, null=True)
    text = models.TextField(null=True, blank=True)
    next_question = models.ForeignKey('self', on_delete=models.CASCADE, related_name="next", blank=True, null=True)
    function_name = models.CharField(max_length=128, null=True, blank=True)

    def __str__(self):
        return self.name

class Answer(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    hack = models.ForeignKey(Hack, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="question", blank=True, null=True)
    correct_answer = models.BigIntegerField(blank=True, null=True)
    score = models.IntegerField(default = 0)
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.character.name


    

app/jurassichack/forms.py
from django import forms

from .models import Character

class StartForm(forms.Form):
    character_name = forms.CharField(label='Character Name')

class InputForm(forms.Form):
    input = forms.IntegerField(label='Console Input')

app/jurassichack/views.py
from django.shortcuts import render
from .forms import StartForm, InputForm
from django.http import HttpResponseRedirect, HttpResponse
from .models import Character, Hack, Question, Answer
from django.utils.timezone import now
from django.core.exceptions import ObjectDoesNotExist
from .utils import jurassichack
import math
from collections import OrderedDict
import itertools
from django.contrib.auth.decorators import login_required

def calculate_score(answers):

    total_score = 0
    for answer in answers:

        answer.completed_at = now()
        answer.save()

        time_to_complete = (answer.completed_at - answer.started_at).total_seconds()
        score = 900 * math.exp(-time_to_complete/900) + 100
        score = int(score)

        total_score += score

    return total_score

def check_for_collaborators(hack, value):
    # Fetch all answers for the given hack and question where completed_at is None
    answers = [x for x in Answer.objects.filter(hack=hack, completed_at=None)]

    print(answers)
    
    # Get the total number of answers with no completed_at
    num_answers = len(answers)
    print("num_answers:", num_answers)

    r = 5
    if r > num_answers:
        r = num_answers

    # Start checking from r = num_answers and decrease r until 1
    for r in range(r, 0, -1):
        print("r=", r)
        # Iterate over all combinations of r answers
        for combo in itertools.combinations(answers, r):
            print("combo:", combo)
            # Calculate the sum of the scores in the current combination
            score_sum = sum(answer.correct_answer for answer in combo)

            print("score_sum:", score_sum)
            
            # If the sum matches the value, return the combination of answers
            if score_sum == value:
                return combo
    
    # If no combination is found, return None
    return None

def get_rankings(hack):
    answers = Answer.objects.filter(hack=hack)
    characters = set(x.character for x in answers)

    rankings_table = {}

    for character in characters:
        rankings_table[character.name] = sum([x.score for x in answers.filter(character=character)])

    return OrderedDict(sorted(rankings_table.items(), reverse=True))

def get_current_hack():
    current_time = now()
    hack = Hack.objects.filter(start__lt = current_time, finish__gt = current_time).first()
    return hack

    
def index(request):

    form = StartForm()

    context = {}

    if request.method == "POST":
        start_form = StartForm(request.POST)
        if start_form.is_valid():
            # Capture the character_name from the form
            character_name = start_form.cleaned_data["character_name"]

            try:
                character = Character.objects.get(name=character_name.lower())
            except ObjectDoesNotExist:
                start_form.add_error(None, "Character does not exist.")
                context["form"] = start_form
                return render(request, "jurassichack/index.html", context)

            hack = get_current_hack()

            if hack is None:
                # Add a form error if no active Hack is found
                start_form.add_error(None, "No Hack is available at the moment.")
                context["form"] = start_form
                return render(request, "jurassichack/index.html", context)
            
            try:
                question = Question.objects.get(name="question_1")
            except ObjectDoesNotExist:
                start_form.add_error(None, "Error. First question is missing!")
                context["form"] = start_form
                return render(request, "jurassichack/index.html", context)
            
            # Try and get existing answer
            try:
                answer = Answer.objects.get(character=character, hack=hack, question=question)
                return HttpResponseRedirect(f'{character.name}/')
            except ObjectDoesNotExist:
            
                # generate_correct_answer
                function = getattr(jurassichack, question.function_name)


                correct_answer = function(character, get_answer=True)

                answer = Answer(
                    character = character,
                    hack = hack,
                    question = question,
                    correct_answer = correct_answer
                )
                answer.save()

                return HttpResponseRedirect(f'{character.name}/')

    context["form"] = form

    return render(request, "jurassichack/index.html", context)


def character(request, character_name):

    hack = get_current_hack()

    try:
        character = Character.objects.get(name=character_name)

        answers = Answer.objects.filter(hack=hack, character=character)

        current_score = sum([x.score for x in answers])
        
        rankings = get_rankings(hack)

        current_rank = list(rankings.keys()).index(character_name) + 1

        answer = answers.last()

        context = {
            "character": character, 
            "answer": answer, 
            "current_score": current_score,
            "current_rank": current_rank
            }

        return render(request, "jurassichack/character.html", context)
        
    except (ObjectDoesNotExist, ValueError):
        start_form = StartForm()
        context = {"form": start_form}
        return render(request, "jurassichack/index.html", context)
    

    

def input(request, answer_id):

    answer = Answer.objects.get(id=answer_id)
    function_name = answer.question.function_name

    # get function from function_name
    function = getattr(jurassichack, function_name)

    html = function(answer.character)
    

    return HttpResponse(html, content_type='text/plain')

def console(request):

    context = {}

    hack = get_current_hack()

    rankings_table = get_rankings(hack)
    context["rankings"] = rankings_table

    if request.method == "POST":
        input_form = InputForm(request.POST)
        if input_form.is_valid():
            value = input_form.cleaned_data["input"]
            #try:
            results = check_for_collaborators(hack, value)
            if results:
                
                score = calculate_score(results)

                user_list = ""

                # update scores
                for answer in results:
                    answer.score = score
                    answer.save()
                    user_list += f"<li>{answer.character.name}</li>"

                
                for answer in results:

                    message = "<strong>Well done:</strong><ul>{0}</ul><p>You've scored <strong>{1}</strong> points!".format(user_list, score)
                    context["message"] = message
                

                    # generate_correct_answer
                    function = getattr(jurassichack, answer.question.next_question.function_name)


                    correct_answer = function(answer.character, get_answer=True)

                    new_answer = Answer(
                            character = answer.character,
                            hack = answer.hack,
                            question = answer.question.next_question,
                            correct_answer = correct_answer,
                            score = 0
                        )
                    
                    new_answer.save()
            


            rankings_table = get_rankings(hack)
            context["form"] = InputForm()
            context["rankings"] = rankings_table
            return render(request, "jurassichack/console.html", context)
            # except:
            #     #input_form.add_error(None, "Ah, ah, ah! You didn't say the magic word.")
            #     context["error"] = "<iframe src='https://giphy.com/embed/3ohzdQ1IynzclJldUQ' width='300' height='auto' style='' frameBorder='0' class='giphy-embed' allowFullScreen></iframe><p>"
            #     context["form"] = input_form
            #     return render(request, "jurassichack/console.html", context)

    rankings_table = get_rankings(hack)
    context["form"] = InputForm()
    context["rankings"] = rankings_table

    return render(request, "jurassichack/console.html", context)

@login_required
def reset(request):

    hack = get_current_hack()
    answers = Answer.objects.filter(hack=hack)
    answers.delete()

    return HttpResponseRedirect('/jurassichack')

app/jurassichack/templates/jurassichack/base.html
<!-- FILEPATH: /c:/Users/treharne/Documents/canvaswizzards/app/app/templates/app/index.html -->
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HiPy_2.0</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/jurassichack.css' %}">

    <link href="https://fonts.cdnfonts.com/css/jurassic-park" rel="stylesheet">
                
    {% block css %}
    {% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,200;9..40,300;9..40,500;9..40,600&display=swap" rel="stylesheet">
    <!-- Add JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,200;9..40,300;9..40,500;9..40,600&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <!-- Confetti-->
    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.2/dist/confetti.browser.min.js"></script>

    
</head>

<body data-spy="scroll" data-target=".navbar">
    
    {% block content %}
    {% endblock %}

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>
                        HiPy was created in 2016 by a group of really cool students and researchers at the university of Liverpool.
                        The surviving founders, Robert Treharne and Sam Ball still believe passionately in the original mission to 
                        build an inclusive, friendly community that helps people learn to code for free.
                    </p>
                </div>
            </div>
        </div>
    </footer>


    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


    {% block js %}
    {% endblock %}
</body>

</html>

app/jurassichack/templates/jurassichack/character.html
{% extends "jurassichack/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="jumbotron page-section" id="event">
    <section class="container">

        <span class="jurassic-hack-logo"><a href="/jurassichack">Jurassic Hack</a></span>

        <br>

        <div class="row">
            <div class="col-md-6">
                <!-- <h3>{{ answer.question.name }}</h3>
                <p>Character: {{ character.name }}</p>
                <p>Current score: {{ current_score }}</p>
                <p>Current rank: {{ current_rank }}</p>
                <p>Text: {{ answer.question.text }}</p> -->
                <h3>{{ answer.question.title }}</h3>
                <div class="task">
                    {{ answer.question.text|safe}}
                </div>
                <p>
                    [<u><a href="/jurassichack/input/{{ answer.id }}/" target="_blank">Input File</a></u>]
                </p>
            </div>

            <div class="col-md-6">
                Resources
            </div>
        </div>
    </section>
</div>

{% endblock %}

app/jurassichack/templates/jurassichack/console.html
{% extends "jurassichack/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="jumbotron page-section" id="event">
    <section class="container">

        <span class="jurassic-hack-logo"><a href="/jurassichack">Jurassic Hack</a></span>

        <br>

        <div class="row">
            <div class="col-md-6">

                {% if message %}
                    <p>{{ message|safe }}</p>
                {% endif %}

                <form method="post" action="{% url 'jurassichack:console' %}">
                    {% csrf_token %}
            
                    {{ form|crispy }}
            
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                
                
            </div>

            <div class="col-md-6">
                {% if error %}
                <p><strong>Your answer is incorrect. Try again.</strong></p>
                    {{ error|safe }}
                {% else %}
                    <div>
                        <table >
                            <tbody>
                                {% for key, value in rankings.items %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ key }}</td>
                                    <td>{{ value }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                
                
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
</div>






{% endblock %}

app/jurassichack/templates/jurassichack/index.html
{% extends "jurassichack/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<header class="jumbotron page-section" id="home">
    <div class="container" >
        <span class="main-logo">Jurassic Hack</span>

        <form method="post" action="{% url 'jurassichack:index' %}">
            {% csrf_token %}
    
            {{ form|crispy }}
    
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>


</header>




{% endblock %}